### ISSUE TITLE
Document local development environment better

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#84]
* Describe how to setup a local dev environment:
* Configure cors

sites/default/services.yml
```
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['*']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['*']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['*']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: true
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
```
* Grant permissions: "administer site configuration" "administer users"
